package model

type Number int

const (
	NUMBER_ACE   = 1
	NUMBER_TWO   = 2
	NUMBER_THREE = 3
	NUMBER_FOUR  = 4
	NUMBER_FIVE  = 5
	NUMBER_SIX   = 6
	NUMBER_SEVEN = 7
	NUMBER_EIGHT = 8
	NUMBER_NINE  = 9
	NUMBER_TEN   = 10
	NUMBER_JACK  = 11
	NUMBER_QUEEN = 12
	NUMBER_KING  = 13
)
